---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: new-pv
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  hostPath:
    path: /mnt/data
...
