---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    app: appserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appserver
  template:
    metadata:
      name: tomcat-pod
      labels:
        app: appserver
    spec:
      containers:
        - name: mytomcat
          image: tomee
      tolerations:
        - key: slave2
          value: intelliqit2
          effect: NoSchedule
          operator: Equal
...
